<a href="https://colab.research.google.com/github/brunaguedes92/LogProgPythonN2/blob/main/Atividade2_Pratica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LISTA DE EXERCÍCIOS

1. Faça o que se pede:
a. Crie uma lista, chamada salario, com os seguintes valores:

[4650, 2360, 1300, 8200, 9600]

b. Verifique o tipo da variável salario para confirmar se é uma lista.
c. Acesse o segundo e terceiro valor da lista salario usando fatiamento.
d. Transforme a lista salario em um array, chamado salario_arrray, usando a
biblioteca do numpy.
e. Verifique o tipo da variável salario_array.
f. Acesse o segundo e terceiro valor de salario_array.
g. Retorne, usando operação booleana, apenas os salários maiores que R$7000.



In [ ]:
salario = [4650, 2360, 1300, 8200, 9600]
type(salario)

list

In [ ]:
salario[1:3]

[2360, 1300]

In [ ]:
import numpy as np

salario_array = np.array(salario)
print(type(salario_array))

<class 'numpy.ndarray'>


In [ ]:
salario_array[1:3]

array([2360, 1300])

In [ ]:
print(salario_array[salario_array>7000])

[8200 9600]


2. A partir do seguinte array contendo as seguintes informações relacionadas ao prêmio
Nobel:
nobel = np.array([
['Adolf Butenandt','1939','Germany','Chemistry','Man'],
['Adolf Otto Reinhold Windaus','1928','Germany','Chemistry','Man'],
['Adolf von Baeyer','1905','Germany','Chemistry','Man'],
['Adolfo Pérez Esquivel','1980','Argentina','Peace','Man'],
['Aung San Suu Kyi','1991','Burma','Peace','Woman'],
['Barbara McClintock','1983','United States', 'Medicine','Woman'],
['Bertha von Suttner','1905','Czech Republic','Peace','Woman'],
['Alice Munro','2013','Canada','Literature','Woman'],
['Alva Myrdal','1982','Sweden','Peace','Woman'],
['Ada Yonath','2009','Israel','Chemistry','Woman']
])
Crie um novo array, chamado mulheres_nobel, cujo conteúdo será o fatiamento do
array nobel original, com apenas os nomes das mulheres e anos de premiação.

In [2]:
import numpy as np

nobel = np.array([
['Adolf Butenandt','1939','Germany','Chemistry','Man'],
['Adolf Otto Reinhold Windaus','1928','Germany','Chemistry','Man'],
['Adolf von Baeyer','1905','Germany','Chemistry','Man'],
['Adolfo Pérez Esquivel','1980','Argentina','Peace','Man'],
['Aung San Suu Kyi','1991','Burma','Peace','Woman'],
['Barbara McClintock','1983','United States', 'Medicine','Woman'],
['Bertha von Suttner','1905','Czech Republic','Peace','Woman'],
['Alice Munro','2013','Canada','Literature','Woman'],
['Alva Myrdal','1982','Sweden','Peace','Woman'],
['Ada Yonath','2009','Israel','Chemistry','Woman']
])

mulheres_nobel = nobel[nobel[:,4] == 'Woman']
print(mulheres_nobel)

[['Aung San Suu Kyi' '1991' 'Burma' 'Peace' 'Woman']
 ['Barbara McClintock' '1983' 'United States' 'Medicine' 'Woman']
 ['Bertha von Suttner' '1905' 'Czech Republic' 'Peace' 'Woman']
 ['Alice Munro' '2013' 'Canada' 'Literature' 'Woman']
 ['Alva Myrdal' '1982' 'Sweden' 'Peace' 'Woman']
 ['Ada Yonath' '2009' 'Israel' 'Chemistry' 'Woman']]


3. Usando o array mulheres_nobel (questão 2), faça um código para mostrar os nomes
das mulheres, em ordem alfabética, seguidos dos anos das suas premiações (dica: use
argsort()).


In [ ]:
print(mulheres_nobel[mulheres_nobel[:,0].argsort()][:,0:2])

[['Ada Yonath' '2009']
 ['Alice Munro' '2013']
 ['Alva Myrdal' '1982']
 ['Aung San Suu Kyi' '1991']
 ['Barbara McClintock' '1983']
 ['Bertha von Suttner' '1905']]


4. Com o novo array mulheres_nobel (questão 2), faça um código que realize uma
operação booleana, indicando quais anos, após o ano 2000, as mulheres ganharam
prêmio nobel - após uma conversão de tipo (como o slide 15).


In [16]:
anos = mulheres_nobel[:,1] > 2000
anos

TypeError: ignored

In [22]:
anos = mulheres_nobel[:,1]
print(anos)

anos_int = anos.astype('int')
print(anos_int)

['1991' '1983' '1905' '2013' '1982' '2009']
[1991 1983 1905 2013 1982 2009]


In [23]:
print(anos_int[anos_int > 2000])

[2013 2009]


5. Considerando o array dos anos de premiação, obtido na questão 4, faça um
código que permita:
a) Exibir o ano mais recente que teve premiação.
b) Exibir o ano do prêmio nobel mais antigo.
c) Calcular a média dos anos anteriores a 2000 e substituir os valores desses
anos pela média obtida.

In [32]:
print(f'Ano mais recente', anos_int.max())
print(f'Ano mais antigo',anos_int.min())
print(f'Média dos anos',anos_int.mean())
print(f'Média dos anos anteriores a 2000',anos_int[anos_int < 2000].mean())
anos_int[anos_int < 2000] = anos_int[anos_int < 2000].mean()

print(anos_int)

Ano mais recente 2013
Ano mais antigo 1905
Média dos anos 1980.5
Média dos anos anteriores a 2000 1965.25
[1965 1965 1965 2013 1965 2009]


**EXTRA**

LISTA DE EXERCÍCIOS

Considerando as informações relacionadas ao prêmio Nobel:
nobel = np.array([
['Adolf Butenandt','1939','Germany','Chemistry','Man'],
['Adolf Otto Reinhold Windaus','1928','Germany','Chemistry','Man'],
['Adolf von Baeyer','1905','Germany','Chemistry','Man'],
['Adolfo Pérez Esquivel','1980','Argentina','Peace','Man'],
['Ada Yonath','2009','Israel','Chemistry','Woman'],
['Alice Munro','2013','Canada','Literature','Woman'],
['Alva Myrdal','1982','Sweden','Peace','Woman'],
['Aung San Suu Kyi','1991','Burma','Peace','Woman'],
['Barbara McClintock','1983','United States', 'Medicine','Woman'],
['Bertha von Suttner','1905','Czech Republic','Peace','Woman']
])
Faça o que se pede:
1. Verifique quantas linhas e colunas tem no array nobel.
2. Crie um novo array, com os nomes dos premiados e anos de premiação (dica: use
fatiamento).
3. Com o resultado obtido na questão 2, liste apenas os nomes em ordem crescente
(dica: crie um array só com os nomes e use o sort()).
4. Liste os nomes em ordem decrescente.
5. Liste os anos de premiação após os anos 2000.

In [49]:
print(f'Linhas e colunas do array nobel.', nobel.shape)
print(f'Novo array, com os nomes dos premiados e anos de premiação.', nobel[:,0:2])
nome_e_ano = nobel[:,0:2]


Linhas e colunas do array nobel. (10, 5)
Novo array, com os nomes dos premiados e anos de premiação. [['Ada Yonath' '1905']
 ['Adolf Butenandt' '1905']
 ['Adolf Otto Reinhold Windaus' '1928']
 ['Adolf von Baeyer' '1939']
 ['Adolfo Pérez Esquivel' '1980']
 ['Alice Munro' '1982']
 ['Alva Myrdal' '1983']
 ['Aung San Suu Kyi' '1991']
 ['Barbara McClintock' '2009']
 ['Bertha von Suttner' '2013']]


In [48]:
print(f'Nomes em ordem crescente', nome_e_ano[nome_e_ano[:,0].argsort()][:,0])

Nomes em ordem crescente ['Ada Yonath' 'Adolf Butenandt' 'Adolf Otto Reinhold Windaus'
 'Adolf von Baeyer' 'Adolfo Pérez Esquivel' 'Alice Munro' 'Alva Myrdal'
 'Aung San Suu Kyi' 'Barbara McClintock' 'Bertha von Suttner']


In [52]:
nomes = nome_e_ano[:,0]
print(f'Nomes em ordem crescente', np.sort(nomes))

Nomes em ordem crescente ['Ada Yonath' 'Adolf Butenandt' 'Adolf Otto Reinhold Windaus'
 'Adolf von Baeyer' 'Adolfo Pérez Esquivel' 'Alice Munro' 'Alva Myrdal'
 'Aung San Suu Kyi' 'Barbara McClintock' 'Bertha von Suttner']


In [54]:
print(f'Nomes em ordem decrescente', np.sort(nomes)[::-1])

Nomes em ordem crescente ['Bertha von Suttner' 'Barbara McClintock' 'Aung San Suu Kyi'
 'Alva Myrdal' 'Alice Munro' 'Adolfo Pérez Esquivel' 'Adolf von Baeyer'
 'Adolf Otto Reinhold Windaus' 'Adolf Butenandt' 'Ada Yonath']


In [61]:
anos = nome_e_ano[:,1].astype('int')

print(f'Liste os anos de premiação após os anos 2000.', anos[anos > 2000])

Liste os anos de premiação após os anos 2000. [2009 2013]
